licornecategorie_index:
    path:     /
    defaults: { _controller: "LicornesBundle:LicorneCategorie:index" }
    methods:  GET

licornecategorie_show:
    path:     /{id}/show
    defaults: { _controller: "LicornesBundle:LicorneCategorie:show" }
    methods:  GET

licornecategorie_new:
    path:     /new
    defaults: { _controller: "LicornesBundle:LicorneCategorie:new" }
    methods:  [GET, POST]

licornecategorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "LicornesBundle:LicorneCategorie:edit" }
    methods:  [GET, POST]

licornecategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "LicornesBundle:LicorneCategorie:delete" }
    methods:  DELETE
