<?php

namespace LicornesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicorneCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicorneCategorieRepository extends EntityRepository
{
}
