licornes_licorne:
    resource: "@LicornesBundle/Resources/config/routing/licorne.yml"
    prefix:   /licorne

licornes_homepage:
    path:     /
    defaults: { _controller: LicornesBundle:Default:index }
